import "@repo/ui/styles.css"
import "./globals.css"
import type { Metadata } from "next"
import { instrumentSerif, inter, jetbrainsMono, sfPro } from "@/lib/fonts"

import Provider from "./provider"

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      className={`${inter.variable} ${sfPro.variable} ${instrumentSerif.variable} ${jetbrainsMono.variable}`}
      lang="en"
      suppressHydrationWarning
    >
      <body className="flex min-h-screen flex-col">
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
